apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}
  annotations:
    kubernetes.io/allow-mixed-protocol: "true"
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns1
      protocol: TCP
      name: dns1
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-udp
  annotations:
    kubernetes.io/allow-mixed-protocol: "true"
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns2
      protocol: UDP
      name: dns2
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
